default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost  # Specify the PostgreSQL host (change if necessary)
  username: postgres  # Replace with your PostgreSQL username
  password: 1234  # Replace with your PostgreSQL password
  port: 5432  # Specify the PostgreSQL port (change if necessary)

development:
  <<: *default
  database: lifegivers_server_development

test:
  <<: *default
  database: lifegivers_server_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
